routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//--------------------- TESTS -------------------------

Route::get('/test_discounts', 'TestController@test_discounts');
//Route::get('/test_activity', 'TestController@test_activity');
//Route::get('/test_trashed_products', 'TestController@test_trashed_products');
//Route::get('/test_pajam_counts', 'TestController@test_pajam_counts');
//Route::get('/test_order_to_transaction/{order_id}', 'Shop\PointOfSaleController@order_to_transactions');
//-----------------------------------------------------



//------------------ FRONT-END (point of sale) --------------------------
Route::get('/point-of-sale', 'Shop\PointOfSaleController@index')->name('point-of-sale');
Route::get('/point-of-sale-test', 'Shop\PointOfSaleController@index_test')->name('point-of-sale-test');

Route::get('/shop', 'AppJsController@shop_app')->name('shop-app-js');
Route::get('/shop-pos', 'AppJsController@shop_pos_app')->name('shop-pos-app-js');
//-----------------------------------------------------------------------



//----------------- POINT OF SALE API ----------------------------
Route::get('/get_user_id', 'Shop\PointOfSaleController@get_user_id');

Route::get('/get_categories/{parent_id}', 'Shop\PointOfSaleController@get_categories');
Route::get('/get_products', 'Shop\PointOfSaleController@get_products');
Route::get('/get_cart_products/{user_id}', 'Shop\PointOfSaleController@get_cart_products');
Route::get('/get_products_by_category/{category_id}', 'Shop\PointOfSaleController@get_products_by_category');
Route::get('/get_breadcrumb/{category_id}', 'Shop\PointOfSaleController@get_breadcrumb');

//Save Order, Order Items, order status=1, Products--, 
Route::post('/save_order', 'Shop\PointOfSaleController@save_order');

Route::post('/save_to_cart', 'Shop\PointOfSaleController@save_to_cart');
Route::post('/delete_product_from_cart', 'Shop\PointOfSaleController@delete_product_from_cart');
Route::delete('/empty_cart', 'Shop\PointOfSaleController@empty_cart');

Route::get('/get_first_order', 'Shop\PointOfSaleController@get_first_order');
Route::get('/get_first_pos_action', 'Shop\PointOfSaleController@get_first_pos_action');

Route::get('/get_orders', 'Shop\PointOfSaleController@get_orders');
Route::get('/get_order_items/{order_id}', 'Shop\PointOfSaleController@get_order_items');

//------ POS APARATAS ----------
//POS api(order update status=2)
Route::get('/order_generated/{order_id}', 'Shop\PointOfSaleController@order_generated');

//POS api(order update status=3; order_to_transactions)
Route::get('/order_printed/{order_id}/{status_code}', 'Shop\PointOfSaleController@order_printed');

//POS api(order update status=-1)
//Route::get('/order_canceled/{order_id}', 'Shop\PointOfSaleController@order_canceled');
Route::get('/order_canceled/{order_id}/{status_code}', 'Shop\PointOfSaleController@order_canceled');

//---pos actions
Route::post('/pos_action_insert', 'Shop\PointOfSaleController@pos_action_insert');
Route::get('/pos_action_callback', 'Shop\PointOfSaleController@pos_action_callback');

Route::get('/pos_action_change_status_success', 'Shop\PointOfSaleController@pos_action_change_status_success');

Route::get('/pos_action_update_order_status', 'Shop\PointOfSaleController@pos_action_update_order_status');

Route::get('/pos_action_disable_all', 'Shop\PointOfSaleController@pos_action_disable_all');
//------------------------------------------------------------------



//------------------- ADMIN ------------------------------

Route::get('/admin', 'HomeController@index')->name('admin');

//Route::get('/admin/inventory', 'InventoryController@index')->name('inventory.index');
Route::resource('admin/inventory', 'InventoryController');

Route::resource('admin/pajamavimas', 'GoodsReceivingController');
Route::post('/admin-ajax', 'AjaxController@index')->name('admin-ajax'); //AJAX route

Route::resource('admin/products', 'ProductController');
Route::resource('admin/categories', 'CategoryController');
Route::resource('admin/pvmGroups', 'PvmGroupController');
Route::resource('admin/measures', 'MeasureController');

Route::resource('admin/suppliers', 'SupplierController');
Route::resource('admin/supplierDocuments', 'SupplierDocumentController');

Route::resource('admin/roles', 'RoleController');
Route::resource('admin/users', 'UserController');

Route::resource('admin/customers', 'CustomerController');
Route::resource('admin/receipts', 'ReceiptController');

Route::resource('admin/innerDocuments', 'InnerDocumentController');
Route::resource('admin/transactions', 'TransactionController');
Route::resource('admin/types', 'TypeController');

Route::prefix('admin/trash')->group(function(){
	Route::get('/', 'TrashController@index')->name('trash.index');

	//Categories
	Route::get('categories', 'CategoryController@trash')->name('trash.categories');
	Route::patch('categories/{id}', 'CategoryController@restore')->name('trash.categories.restore');

	//Products
	Route::get('products', 'ProductController@trash')->name('trash.products');
	Route::patch('products/{id}', 'ProductController@restore')->name('trash.products.restore');	
});

Route::resource('admin/permissions', 'PermissionController');

Route::get('/admin/reports', 'ReportsController@reports')->name('reports.index');
Route::get('/admin/reports/purchase', 'ReportsController@reports_purchase')->name('reports.purchase');
Route::get('/admin/reports/sale', 'ReportsController@reports_sale')->name('reports.sale');
Route::get('/admin/reports/inventory', 'ReportsController@reports_inventory')->name('reports.inventory');
Route::get('/admin/reports/inventory/{id}', 'ReportsController@reports_inventory_show')->name('reports.inventory.show');

Route::get('/admin/orders', 'OrderController@index')->name('orders.index');
Route::get('/admin/order-items/{order_id}', 'OrderController@order_items')->name('order.items');
//----------------------------------------------------------------------------

app/Models/InnerDocument.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class InnerDocument
 * @package App\Models
 * @version November 24, 2017, 10:11 am UTC
 *
 * @property string file
 * @property string description
 */
class InnerDocument extends Model
{
    use SoftDeletes;

    public $table = 'inner_documents';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'file',
        'description'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'file' => 'string',
        'description' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/InnerDocumentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateInnerDocumentRequest;
use App\Http\Requests\UpdateInnerDocumentRequest;
use App\Repositories\InnerDocumentRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class InnerDocumentController extends AppBaseController
{
    /** @var  InnerDocumentRepository */
    private $innerDocumentRepository;

    public function __construct(InnerDocumentRepository $innerDocumentRepo)
    {
        $this->middleware('auth');

        $this->middleware('can:view-inner-documents');

        $this->innerDocumentRepository = $innerDocumentRepo;
    }

    /**
     * Display a listing of the InnerDocument.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->innerDocumentRepository->pushCriteria(new RequestCriteria($request));
        $innerDocuments = $this->innerDocumentRepository->all();

        return view('admin.inner_documents.index')
            ->with('innerDocuments', $innerDocuments);
    }

    /**
     * Show the form for creating a new InnerDocument.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.inner_documents.create');
    }

    /**
     * Store a newly created InnerDocument in storage.
     *
     * @param CreateInnerDocumentRequest $request
     *
     * @return Response
     */
    public function store(CreateInnerDocumentRequest $request)
    {
        $input = $request->all();

        $innerDocument = $this->innerDocumentRepository->create($input);

        Flash::success('Inner Document saved successfully.');

        return redirect(route('innerDocuments.index'));
    }

    /**
     * Display the specified InnerDocument.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $innerDocument = $this->innerDocumentRepository->findWithoutFail($id);

        if (empty($innerDocument)) {
            Flash::error('Inner Document not found');

            return redirect(route('innerDocuments.index'));
        }

        return view('admin.inner_documents.show')->with('innerDocument', $innerDocument);
    }

    /**
     * Show the form for editing the specified InnerDocument.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $innerDocument = $this->innerDocumentRepository->findWithoutFail($id);

        if (empty($innerDocument)) {
            Flash::error('Inner Document not found');

            return redirect(route('innerDocuments.index'));
        }

        return view('admin.inner_documents.edit')->with('innerDocument', $innerDocument);
    }

    /**
     * Update the specified InnerDocument in storage.
     *
     * @param  int              $id
     * @param UpdateInnerDocumentRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateInnerDocumentRequest $request)
    {
        $innerDocument = $this->innerDocumentRepository->findWithoutFail($id);

        if (empty($innerDocument)) {
            Flash::error('Inner Document not found');

            return redirect(route('innerDocuments.index'));
        }

        $innerDocument = $this->innerDocumentRepository->update($request->all(), $id);

        Flash::success('Inner Document updated successfully.');

        return redirect(route('innerDocuments.index'));
    }

    /**
     * Remove the specified InnerDocument from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $innerDocument = $this->innerDocumentRepository->findWithoutFail($id);

        if (empty($innerDocument)) {
            Flash::error('Inner Document not found');

            return redirect(route('innerDocuments.index'));
        }

        $this->innerDocumentRepository->delete($id);

        Flash::success('Inner Document deleted successfully.');

        return redirect(route('innerDocuments.index'));
    }
}

resources/views/admin/inner_documents/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            @lang('layouts/menu.inner_document')
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'innerDocuments.store']) !!}

                        @include('admin.inner_documents.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/inner_documents/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            @lang('layouts/menu.inner_document')
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($innerDocument, ['route' => ['innerDocuments.update', $innerDocument->id], 'method' => 'patch']) !!}

                        @include('admin.inner_documents.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/admin/inner_documents/fields.blade.php
<!-- File Field -->
<div class="form-group col-sm-6">
    {!! Form::label('file', Lang::get('base.file').':') !!}
    {!! Form::text('file', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('description', Lang::get('base.description').':') !!}
    {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit(Lang::get('base.save'), ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('innerDocuments.index') !!}" class="btn btn-default">@lang('base.cancel')</a>
</div>

resources/views/admin/inner_documents/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">@lang('layouts/menu.inner_documents')</h1>
        <h1 class="pull-right">
            <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('innerDocuments.create') !!}">
                @lang('base.add_new')
            </a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('admin.inner_documents.table')
            </div>
        </div>
    </div>
@endsection

resources/views/admin/inner_documents/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Inner Document
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('admin.inner_documents.show_fields')
                    <a href="{!! route('innerDocuments.index') !!}" class="btn btn-default">@lang('base.back')</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/inner_documents/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $innerDocument->id !!}</p>
</div>

<!-- File Field -->
<div class="form-group">
    {!! Form::label('file', 'File:') !!}
    <p>{!! $innerDocument->file !!}</p>
</div>

<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', 'Description:') !!}
    <p>{!! $innerDocument->description !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $innerDocument->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $innerDocument->updated_at !!}</p>
</div>

resources/views/admin/inner_documents/table.blade.php
<table class="table table-responsive" id="innerDocuments-table">
    <thead>
        <tr>
            <th>@lang('base.file')</th>
            <th>@lang('base.description')</th>
            <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
    @foreach($innerDocuments as $innerDocument)
        <tr>
            <td>{!! $innerDocument->file !!}</td>
            <td>{!! $innerDocument->description !!}</td>
            <td>
                {!! Form::open(['route' => ['innerDocuments.destroy', $innerDocument->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('innerDocuments.show', [$innerDocument->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('innerDocuments.edit', [$innerDocument->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>