routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//--------------------- TESTS -------------------------

Route::get('/test_discounts', 'TestController@test_discounts');
//Route::get('/test_activity', 'TestController@test_activity');
//Route::get('/test_trashed_products', 'TestController@test_trashed_products');
//Route::get('/test_pajam_counts', 'TestController@test_pajam_counts');
//Route::get('/test_order_to_transaction/{order_id}', 'Shop\PointOfSaleController@order_to_transactions');
//-----------------------------------------------------



//------------------ FRONT-END (point of sale) --------------------------
Route::get('/point-of-sale', 'Shop\PointOfSaleController@index')->name('point-of-sale');
Route::get('/point-of-sale-test', 'Shop\PointOfSaleController@index_test')->name('point-of-sale-test');

Route::get('/shop', 'AppJsController@shop_app')->name('shop-app-js');
Route::get('/shop-pos', 'AppJsController@shop_pos_app')->name('shop-pos-app-js');
//-----------------------------------------------------------------------



//----------------- POINT OF SALE API ----------------------------
Route::get('/get_user_id', 'Shop\PointOfSaleController@get_user_id');

Route::get('/get_categories/{parent_id}', 'Shop\PointOfSaleController@get_categories');
Route::get('/get_products', 'Shop\PointOfSaleController@get_products');
Route::get('/get_cart_products/{user_id}', 'Shop\PointOfSaleController@get_cart_products');
Route::get('/get_products_by_category/{category_id}', 'Shop\PointOfSaleController@get_products_by_category');
Route::get('/get_breadcrumb/{category_id}', 'Shop\PointOfSaleController@get_breadcrumb');

//Save Order, Order Items, order status=1, Products--, 
Route::post('/save_order', 'Shop\PointOfSaleController@save_order');

Route::post('/save_to_cart', 'Shop\PointOfSaleController@save_to_cart');
Route::post('/delete_product_from_cart', 'Shop\PointOfSaleController@delete_product_from_cart');
Route::delete('/empty_cart', 'Shop\PointOfSaleController@empty_cart');

Route::get('/get_first_order', 'Shop\PointOfSaleController@get_first_order');
Route::get('/get_first_pos_action', 'Shop\PointOfSaleController@get_first_pos_action');

Route::get('/get_orders', 'Shop\PointOfSaleController@get_orders');
Route::get('/get_order_items/{order_id}', 'Shop\PointOfSaleController@get_order_items');

//------ POS APARATAS ----------
//POS api(order update status=2)
Route::get('/order_generated/{order_id}', 'Shop\PointOfSaleController@order_generated');

//POS api(order update status=3; order_to_transactions)
Route::get('/order_printed/{order_id}/{status_code}', 'Shop\PointOfSaleController@order_printed');

//POS api(order update status=-1)
//Route::get('/order_canceled/{order_id}', 'Shop\PointOfSaleController@order_canceled');
Route::get('/order_canceled/{order_id}/{status_code}', 'Shop\PointOfSaleController@order_canceled');

//---pos actions
Route::post('/pos_action_insert', 'Shop\PointOfSaleController@pos_action_insert');
Route::get('/pos_action_callback', 'Shop\PointOfSaleController@pos_action_callback');

Route::get('/pos_action_change_status_success', 'Shop\PointOfSaleController@pos_action_change_status_success');

Route::get('/pos_action_update_order_status', 'Shop\PointOfSaleController@pos_action_update_order_status');

Route::get('/pos_action_disable_all', 'Shop\PointOfSaleController@pos_action_disable_all');
//------------------------------------------------------------------



//------------------- ADMIN ------------------------------

Route::get('/admin', 'HomeController@index')->name('admin');

//Route::get('/admin/inventory', 'InventoryController@index')->name('inventory.index');
Route::resource('admin/inventory', 'InventoryController');

Route::resource('admin/pajamavimas', 'GoodsReceivingController');
Route::post('/admin-ajax', 'AjaxController@index')->name('admin-ajax'); //AJAX route

Route::resource('admin/products', 'ProductController');
Route::resource('admin/categories', 'CategoryController');
Route::resource('admin/pvmGroups', 'PvmGroupController');
Route::resource('admin/measures', 'MeasureController');

Route::resource('admin/suppliers', 'SupplierController');
Route::resource('admin/supplierDocuments', 'SupplierDocumentController');

Route::resource('admin/roles', 'RoleController');
Route::resource('admin/users', 'UserController');

Route::resource('admin/customers', 'CustomerController');
Route::resource('admin/receipts', 'ReceiptController');

Route::resource('admin/innerDocuments', 'InnerDocumentController');
Route::resource('admin/transactions', 'TransactionController');
Route::resource('admin/types', 'TypeController');

Route::prefix('admin/trash')->group(function(){
	Route::get('/', 'TrashController@index')->name('trash.index');

	//Categories
	Route::get('categories', 'CategoryController@trash')->name('trash.categories');
	Route::patch('categories/{id}', 'CategoryController@restore')->name('trash.categories.restore');

	//Products
	Route::get('products', 'ProductController@trash')->name('trash.products');
	Route::patch('products/{id}', 'ProductController@restore')->name('trash.products.restore');	
});

Route::resource('admin/permissions', 'PermissionController');

Route::get('/admin/reports', 'ReportsController@reports')->name('reports.index');
Route::get('/admin/reports/purchase', 'ReportsController@reports_purchase')->name('reports.purchase');
Route::get('/admin/reports/sale', 'ReportsController@reports_sale')->name('reports.sale');
Route::get('/admin/reports/inventory', 'ReportsController@reports_inventory')->name('reports.inventory');
Route::get('/admin/reports/inventory/{id}', 'ReportsController@reports_inventory_show')->name('reports.inventory.show');

Route::get('/admin/orders', 'OrderController@index')->name('orders.index');
Route::get('/admin/order-items/{order_id}', 'OrderController@order_items')->name('order.items');
//----------------------------------------------------------------------------

app/Models/Supplier.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Supplier
 * @package App\Models
 * @version November 23, 2017, 12:03 pm UTC
 *
 * @property string title
 * @property string address
 * @property string name
 * @property string lastname
 * @property string phone
 * @property string code
 * @property string pvm_code
 */
class Supplier extends Model
{
    use SoftDeletes;

    public $appends = ['products, transactions'];

    public $table = 'suppliers';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'title',
        'address',
        'name',
        'lastname',
        'phone',
        'code',
        'pvm_code'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'title' => 'string',
        'address' => 'string',
        'name' => 'string',
        'lastname' => 'string',
        'phone' => 'string',
        'code' => 'string',
        'pvm_code' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'title' => 'required',
    ];

    public function supplier_documents(){
        return $this->hasMany('App\Models\SupplierDocument');
    }

    public function getProductsAttribute(){
        $products = [];

        foreach ($this->supplier_documents as $document) {
            foreach ($document->transactions as $transaction){
                $products[] = $transaction->product;
            }
        }

        return $products;
    }

    public function getTransactionsAttribute(){
        $transactions = [];

        foreach ($this->supplier_documents as $document) {
            foreach ($document->transactions as $transaction){
                $transactions[] = $transaction;
            }
        }

        return $transactions;
    }    

    
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateSupplierRequest;
use App\Http\Requests\UpdateSupplierRequest;
use App\Repositories\SupplierRepository;
use App\Models\Product;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class SupplierController extends AppBaseController
{
    /** @var  SupplierRepository */
    private $supplierRepository;

    public function __construct(SupplierRepository $supplierRepo)
    {
        $this->middleware('auth');

        $this->middleware('can:view-suppliers');

        $this->supplierRepository = $supplierRepo;
    }

    /**
     * Display a listing of the Supplier.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->supplierRepository->pushCriteria(new RequestCriteria($request));
        $suppliers = $this->supplierRepository->all();

        return view('admin.suppliers.index')
            ->with('suppliers', $suppliers);
    }

    /**
     * Show the form for creating a new Supplier.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.suppliers.create');
    }

    /**
     * Store a newly created Supplier in storage.
     *
     * @param CreateSupplierRequest $request
     *
     * @return Response
     */
    public function store(CreateSupplierRequest $request)
    {
        $input = $request->all();

        $supplier = $this->supplierRepository->create($input);

        Flash::success('Supplier saved successfully.');

        return redirect(route('suppliers.index'));
    }

    /**
     * Display the specified Supplier.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $supplier = $this->supplierRepository->findWithoutFail($id);

        if (empty($supplier)) {
            Flash::error('Supplier not found');

            return redirect(route('suppliers.index'));
        }

        $data = [
            'supplier' => $supplier,
            //'products' => $supplier->products,
            'transactions' => $supplier->transactions,
            'supplierDocuments' => $supplier->supplier_documents
        ];

        return view('admin.suppliers.show', $data);
    }

    /**
     * Show the form for editing the specified Supplier.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $supplier = $this->supplierRepository->findWithoutFail($id);

        if (empty($supplier)) {
            Flash::error('Supplier not found');

            return redirect(route('suppliers.index'));
        }

        return view('admin.suppliers.edit')->with('supplier', $supplier);
    }

    /**
     * Update the specified Supplier in storage.
     *
     * @param  int              $id
     * @param UpdateSupplierRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateSupplierRequest $request)
    {
        $supplier = $this->supplierRepository->findWithoutFail($id);

        if (empty($supplier)) {
            Flash::error('Supplier not found');

            return redirect(route('suppliers.index'));
        }

        $supplier = $this->supplierRepository->update($request->all(), $id);

        Flash::success('Supplier updated successfully.');

        return redirect(route('suppliers.index'));
    }

    /**
     * Remove the specified Supplier from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $supplier = $this->supplierRepository->findWithoutFail($id);

        if (empty($supplier)) {
            Flash::error('Supplier not found');

            return redirect(route('suppliers.index'));
        }

        $this->supplierRepository->delete($id);

        Flash::success('Supplier deleted successfully.');

        return redirect(route('suppliers.index'));
    }
}

resources/views/admin/suppliers/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            @lang('layouts/menu.supplier')
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'suppliers.store']) !!}

                        @include('admin.suppliers.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/suppliers/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            @lang('layouts/menu.supplier')
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($supplier, ['route' => ['suppliers.update', $supplier->id], 'method' => 'patch']) !!}

                        @include('admin.suppliers.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/admin/suppliers/fields.blade.php
<!-- Title Field -->
<div class="form-group col-sm-6">
    {!! Form::label('title', Lang::get('base.title').':') !!}
    {!! Form::text('title', null, ['class' => 'form-control']) !!}
</div>

<!-- Address Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('address', Lang::get('base.address').':') !!}
    {!! Form::textarea('address', null, ['class' => 'form-control']) !!}
</div>

<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', Lang::get('base.name').':') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- LastName Field -->
<div class="form-group col-sm-6">
    {!! Form::label('lastname', Lang::get('base.lastname').':') !!}
    {!! Form::text('lastname', null, ['class' => 'form-control']) !!}
</div>

<!-- Phone Field -->
<div class="form-group col-sm-6">
    {!! Form::label('phone', Lang::get('base.phone').':') !!}
    {!! Form::text('phone', null, ['class' => 'form-control']) !!}
</div>

<!-- Code Field -->
<div class="form-group col-sm-6">
    {!! Form::label('code', Lang::get('base.code').':') !!}
    {!! Form::text('code', null, ['class' => 'form-control']) !!}
</div>

<!-- Pvm Code Field -->
<div class="form-group col-sm-6">
    {!! Form::label('pvm_code', Lang::get('base.pvm_code').':') !!}
    {!! Form::text('pvm_code', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit(Lang::get('base.save'), ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('suppliers.index') !!}" class="btn btn-default">@lang('base.cancel')</a>
</div>

resources/views/admin/suppliers/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">@lang('layouts/menu.suppliers')</h1>
        <h1 class="pull-right">
            <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('suppliers.create') !!}">
                @lang('base.add_new')
            </a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('admin.suppliers.table')
            </div>
        </div>
    </div>
@endsection

resources/views/admin/suppliers/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            @lang('layouts/menu.supplier')
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">

            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('admin.suppliers.show_fields')
                    
                </div>
            </div>

        </div>
    </div>

    <div id="transactions">
        <section class="content-header">
            <h1>
                @lang('base.documents') (@lang('layouts/menu.transactions'))
            </h1>
        </section>
        <div  class="content">
            <div class="box box-primary">
          
                <div class="box-body">
                    <div class="row" style="padding-left: 20px">
                        @include('admin.supplier_documents.table')
                        <a href="{!! route('suppliers.index') !!}" class="btn btn-default">@lang('base.back')</a>
                    </div>
                </div>
           
            </div>
        </div>
    </div>

    <!--
    <div id="products-as-transactions">
        <section class="content-header">
            <h1>
                Transactions as products
            </h1>
        </section>
        <div  class="content">
            <div class="box box-primary">
          
                <div class="box-body">
                    <div class="row" style="padding-left: 20px">
                        @include('admin.suppliers.transactions.table')
                        <a href="{!! route('suppliers.index') !!}" class="btn btn-default">Back</a>
                    </div>
                </div>
           
            </div>
        </div>
    </div>  
    -->     
  
@endsection

resources/views/admin/suppliers/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $supplier->id !!}</p>
</div>

<!-- Title Field -->
<div class="form-group">
    {!! Form::label('title', Lang::get('base.title').':') !!}
    <p>{!! $supplier->title !!}</p>
</div>

<!-- Address Field -->
<div class="form-group">
    {!! Form::label('address', Lang::get('base.address').':') !!}
    <p>{!! $supplier->address !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', Lang::get('base.name').':') !!}
    <p>{!! $supplier->name !!}</p>
</div>

<!-- Lastname Field -->
<div class="form-group">
    {!! Form::label('lastname', Lang::get('base.lastname').':') !!}
    <p>{!! $supplier->lastname !!}</p>
</div>

<!-- Phone Field -->
<div class="form-group">
    {!! Form::label('phone', Lang::get('base.phone').':') !!}
    <p>{!! $supplier->phone !!}</p>
</div>

<!-- Code Field -->
<div class="form-group">
    {!! Form::label('code', Lang::get('base.code').':') !!}
    <p>{!! $supplier->code !!}</p>
</div>

<!-- Pvm Code Field -->
<div class="form-group">
    {!! Form::label('pvm_code', Lang::get('base.pvm_code').':') !!}
    <p>{!! $supplier->pvm_code !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', Lang::get('base.created_at').':') !!}
    <p>{!! $supplier->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', Lang::get('base.updated_at').':') !!}
    <p>{!! $supplier->updated_at !!}</p>
</div>

resources/views/admin/suppliers/table.blade.php
<table class="table table-responsive" id="suppliers-table">
    <thead>
        <tr>
            <th>@lang('base.title')</th>
            <th>@lang('base.address')</th>
            <th>@lang('base.name')</th>
            <th>@lang('base.lastname')</th>
            <th>@lang('base.phone')</th>
            <th>@lang('base.code')</th>
            <th>@lang('base.pvm_code')</th>
            <th>@lang('base.documents')</th>

            <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
    @foreach($suppliers as $supplier)
        <tr>
            <td>{!! $supplier->title !!}</td>
            <td>{!! $supplier->address !!}</td>
            <td>{!! $supplier->name !!}</td>
            <td>{!! $supplier->lastname !!}</td>
            <td>{!! $supplier->phone !!}</td>
            <td>{!! $supplier->code !!}</td>
            <td>{!! $supplier->pvm_code !!}</td>

            <td>
                
                @foreach($supplier->supplier_documents as $document)
                    <a href="{{route('supplierDocuments.index')}}/{{$document->id}}"><div class="categories-inline">{{ $document->nr }}</div></a>
                @endforeach
            </td>

            <td>
                {!! Form::open(['route' => ['suppliers.destroy', $supplier->id], 'method' => 'delete']) !!}
                <div class='btn-group'>

                    <a href="{!! route('suppliers.show', [$supplier->id]) !!}" class='btn btn-default'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('suppliers.edit', [$supplier->id]) !!}" class='btn btn-default'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>